/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutBrandRouteImport } from './routes/about.brand'
import { Route as AboutPartnersRouteImport } from './routes/about.partners'
import { Route as AboutMediaRouteImport } from './routes/about.media'
import { Route as AboutContactRouteImport } from './routes/about.contact'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as RosterPlayerIdRouteImport } from './routes/roster.$playerId'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as GamesIndexRouteImport } from './routes/games.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutBrandRoute = AboutBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPartnersRoute = AboutPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AboutRoute,
} as any)
const AboutMediaRoute = AboutMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AboutRoute,
} as any)
const AboutContactRoute = AboutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AboutRoute,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterPlayerIdRoute = RosterPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => RosterRoute,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/$gameId',
  path: '/$gameId',
  getParentRoute: () => GamesRoute,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GamesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/about/brand': typeof AboutBrandRoute
  '/about/partners': typeof AboutPartnersRoute
  '/about/media': typeof AboutMediaRoute
  '/about/contact': typeof AboutContactRoute
  '/games': typeof GamesRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/legal': typeof LegalRoute
  '/matches': typeof MatchesRoute
  '/achievements': typeof AchievementsRoute
  '/settings': typeof SettingsRoute
  '/roster': typeof RosterRouteWithChildren
  '/roster/$playerId': typeof RosterPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/about/brand': typeof AboutBrandRoute
  '/about/partners': typeof AboutPartnersRoute
  '/about/media': typeof AboutMediaRoute
  '/about/contact': typeof AboutContactRoute
  '/games': typeof GamesRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/legal': typeof LegalRoute
  '/matches': typeof MatchesRoute
  '/achievements': typeof AchievementsRoute
  '/settings': typeof SettingsRoute
  '/roster': typeof RosterRouteWithChildren
  '/roster/$playerId': typeof RosterPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/about/brand': typeof AboutBrandRoute
  '/about/partners': typeof AboutPartnersRoute
  '/about/media': typeof AboutMediaRoute
  '/about/contact': typeof AboutContactRoute
  '/games': typeof GamesRouteWithChildren
  '/games/$gameId': typeof GamesGameIdRoute
  '/legal': typeof LegalRoute
  '/matches': typeof MatchesRoute
  '/achievements': typeof AchievementsRoute
  '/settings': typeof SettingsRoute
  '/roster': typeof RosterRouteWithChildren
  '/roster/$playerId': typeof RosterPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/about/' | '/about/brand' | '/about/partners' | '/about/media' | '/about/contact' | '/games' | '/games/$gameId' | '/legal' | '/matches' | '/achievements' | '/settings' | '/roster' | '/roster/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/about/' | '/about/brand' | '/about/partners' | '/about/media' | '/about/contact' | '/games' | '/games/$gameId' | '/legal' | '/matches' | '/achievements' | '/settings' | '/roster' | '/roster/$playerId'
  id: '__root__' | '/' | '/about' | '/about/' | '/about/brand' | '/about/partners' | '/about/media' | '/about/contact' | '/games' | '/games/$gameId' | '/legal' | '/matches' | '/achievements' | '/settings' | '/roster' | '/roster/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  GamesRoute: typeof GamesRouteWithChildren
  LegalRoute: typeof LegalRoute
  MatchesRoute: typeof MatchesRoute
  AchievementsRoute: typeof AchievementsRoute
  SettingsRoute: typeof SettingsRoute
  RosterRoute: typeof RosterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/brand': {
      id: '/about/brand'
      path: '/brand'
      fullPath: '/about/brand'
      preLoaderRoute: typeof AboutBrandRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/partners': {
      id: '/about/partners'
      path: '/partners'
      fullPath: '/about/partners'
      preLoaderRoute: typeof AboutPartnersRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/media': {
      id: '/about/media'
      path: '/media'
      fullPath: '/about/media'
      preLoaderRoute: typeof AboutMediaRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/contact': {
      id: '/about/contact'
      path: '/contact'
      fullPath: '/about/contact'
      preLoaderRoute: typeof AboutContactRouteImport
      parentRoute: typeof AboutRoute
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof GamesRoute
    }
    '/games/': {
      id: '/games/'
      path: '/'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof GamesRoute
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$playerId': {
      id: '/roster/$playerId'
      path: '/$playerId'
      fullPath: '/roster/$playerId'
      preLoaderRoute: typeof RosterPlayerIdRouteImport
      parentRoute: typeof RosterRoute
    }
  }
}

interface AboutRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
  AboutBrandRoute: typeof AboutBrandRoute
  AboutPartnersRoute: typeof AboutPartnersRoute
  AboutMediaRoute: typeof AboutMediaRoute
  AboutContactRoute: typeof AboutContactRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
  AboutBrandRoute: AboutBrandRoute,
  AboutPartnersRoute: AboutPartnersRoute,
  AboutMediaRoute: AboutMediaRoute,
  AboutContactRoute: AboutContactRoute,
}

const AboutRouteWithChildren =
  AboutRoute._addFileChildren(AboutRouteChildren)

interface RosterRouteChildren {
  RosterPlayerIdRoute: typeof RosterPlayerIdRoute
}

const RosterRouteChildren: RosterRouteChildren = {
  RosterPlayerIdRoute: RosterPlayerIdRoute,
}

const RosterRouteWithChildren =
  RosterRoute._addFileChildren(RosterRouteChildren)

interface GamesRouteChildren {
  GamesGameIdRoute: typeof GamesGameIdRoute
  GamesIndexRoute: typeof GamesIndexRoute
}

const GamesRouteChildren: GamesRouteChildren = {
  GamesGameIdRoute: GamesGameIdRoute,
  GamesIndexRoute: GamesIndexRoute,
}

const GamesRouteWithChildren =
  GamesRoute._addFileChildren(GamesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  GamesRoute: GamesRouteWithChildren,
  LegalRoute: LegalRoute,
  MatchesRoute: MatchesRoute,
  AchievementsRoute: AchievementsRoute,
  SettingsRoute: SettingsRoute,
  RosterRoute: RosterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
