/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as RosterPlayerIdRouteImport } from './routes/roster.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterPlayerIdRoute = RosterPlayerIdRouteImport.update({
  id: '/$playerId',
  path: '/$playerId',
  getParentRoute: () => RosterRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legal': typeof LegalRoute
  '/roster': typeof RosterRouteWithChildren
  '/roster/$playerId': typeof RosterPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legal': typeof LegalRoute
  '/roster': typeof RosterRouteWithChildren
  '/roster/$playerId': typeof RosterPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/legal': typeof LegalRoute
  '/roster': typeof RosterRouteWithChildren
  '/roster/$playerId': typeof RosterPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/legal' | '/roster' | '/roster/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/legal' | '/roster' | '/roster/$playerId'
  id: '__root__' | '/' | '/about' | '/legal' | '/roster' | '/roster/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LegalRoute: typeof LegalRoute
  RosterRoute: typeof RosterRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster/$playerId': {
      id: '/roster/$playerId'
      path: '/$playerId'
      fullPath: '/roster/$playerId'
      preLoaderRoute: typeof RosterPlayerIdRouteImport
      parentRoute: typeof RosterRoute
    }
  }
}

interface RosterRouteChildren {
  RosterPlayerIdRoute: typeof RosterPlayerIdRoute
}

const RosterRouteChildren: RosterRouteChildren = {
  RosterPlayerIdRoute: RosterPlayerIdRoute,
}

const RosterRouteWithChildren =
  RosterRoute._addFileChildren(RosterRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LegalRoute: LegalRoute,
  RosterRoute: RosterRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
